CC      ?= gcc
CFLAGS  ?= -O1 -g -std=c99 -Wall -Wextra -Wno-unused-parameter \
           -fsanitize=address,undefined -fno-omit-frame-pointer
SRC      = ../src/game.c ../src/segfont.c ../src/data_tiles.c ../src/data_masks.c \
           ../src/data_maps.c ../src/data_ships.c host_test.c
all: host_test
host_test: $(SRC)
	$(CC) $(CFLAGS) -I../src -o $@ $(SRC)
clean:
	rm -f host_test
.PHONY: all clean
